"""added sqlalchemy.Uuid type for database agnostic uuid.

Revision ID: e20cbb7cc6b3
Revises: 1830265c8730
Create Date: 2025-08-13 00:47:49.009930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20cbb7cc6b3'
down_revision: Union[str, Sequence[str], None] = '1830265c8730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    dialect = bind.dialect.name
    
    if dialect != 'sqlite':
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('blogs', 'id',
                existing_type=sa.VARCHAR(length=36),
                type_=sa.Uuid(),
                existing_nullable=False)
        op.alter_column('blogs', 'author_id',
                existing_type=sa.VARCHAR(length=36),
                type_=sa.Uuid(),
                existing_nullable=False)
        op.alter_column('users', 'id',
                existing_type=sa.VARCHAR(length=36),
                type_=sa.Uuid(),
                existing_nullable=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect = bind.dialect.name
    
    if dialect != 'sqlite':
        op.alter_column('users', 'id',
                existing_type=sa.Uuid(),
                type_=sa.VARCHAR(length=36),
                existing_nullable=False)
        op.alter_column('blogs', 'author_id',
                existing_type=sa.Uuid(),
                type_=sa.VARCHAR(length=36),
                existing_nullable=False)
        op.alter_column('blogs', 'id',
                existing_type=sa.Uuid(),
                type_=sa.VARCHAR(length=36),
                existing_nullable=False)
        # ### end Alembic commands ###
