import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { GetLoggedInUser } from "@/lib/server-utils/getLoggedInUser";
import AdminNav from "@/components/layout/adminNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Blog App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { user } = await GetLoggedInUser();
  // console.log("User in Layout.tsx: ", user);
  
  return (
    <html lang="en">
      <body
        className={
          `${geistSans.variable} ${geistMono.variable} antialiased
          flex flex-col min-h-screen` //items-center justify-between
        }
      >
        <Header user={user} />
        <main className="flex-grow w-full"> {/* max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-12 py-6"> */}
          { user && (
            <div className="w-fit float-right text-right m-10">
              <AdminNav />
            </div>
          )}
          <div className="w-full">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
