from pydantic import BaseModel, Field
import uuid
from datetime import datetime

from .user_schema import UserOut

# Common shared fields for create/update
class BlogBase(BaseModel):
    title: str = Field(..., max_length=200)
    content: str
    is_draft: bool = True

# Fields required when creating
class BlogCreate(BlogBase):
    # id (autogenerated)
    # created_at (autogenerated)
    # updated_at (autogenerated)
    # author (auto-populated)
    pass

# Fields you want to return to the client
class BlogOut(BlogBase):
    id: uuid.UUID
    # author_id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    author: UserOut
    
    class Config:
        from_attributes = True
        
# For PATCH-style updates
class BlogUpdate(BaseModel):
    title: str | None = None
    content: str | None = None
    is_draft: bool | None = None
