from pydantic import BaseModel, Field
import uuid
from datetime import datetime
from typing import List, Optional

from .user_schema import UserOut
from .topic_schema import TopicOut, TopicCreate

# Common shared fields for create/update
class BlogBase(BaseModel):
    title: str = Field(..., max_length=200)
    content: str
    is_draft: bool = True

# Fields required when creating
class BlogCreate(BlogBase):
    # id (autogenerated)
    # created_at (autogenerated)
    # updated_at (autogenerated)
    # author (auto-populated)
    topic_ids: List[uuid.UUID] | None = Field(default_factory=list) # or, uuid.UUID

# Fields you want to return to the client
class BlogOut(BlogBase):
    id: uuid.UUID
    # author_id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    author: UserOut
    topics: List[TopicOut] | None = Field(default_factory=list)
    
    class Config:
        from_attributes = True
        
# For PATCH-style updates
class BlogUpdate(BaseModel):
    title: Optional[str] = Field(None, max_length=200)
    content: str | None = None
    is_draft: bool | None = None
    topic_ids: List[uuid.UUID] | None = None
    